// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: a2b01cac16
// Version Date: 2022-10-20T18:44:52Z

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/mises-id/mises-vpnsvc/proto"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC VpnsvcServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.VpnsvcServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// vpnsvc

		createorder: grpctransport.NewServer(
			endpoints.CreateOrderEndpoint,
			DecodeGRPCCreateOrderRequest,
			EncodeGRPCCreateOrderResponse,
			serverOptions...,
		),
		updateorder: grpctransport.NewServer(
			endpoints.UpdateOrderEndpoint,
			DecodeGRPCUpdateOrderRequest,
			EncodeGRPCUpdateOrderResponse,
			serverOptions...,
		),
		vpninfo: grpctransport.NewServer(
			endpoints.VpnInfoEndpoint,
			DecodeGRPCVpnInfoRequest,
			EncodeGRPCVpnInfoResponse,
			serverOptions...,
		),
		fetchorders: grpctransport.NewServer(
			endpoints.FetchOrdersEndpoint,
			DecodeGRPCFetchOrdersRequest,
			EncodeGRPCFetchOrdersResponse,
			serverOptions...,
		),
		fetchorderinfo: grpctransport.NewServer(
			endpoints.FetchOrderInfoEndpoint,
			DecodeGRPCFetchOrderInfoRequest,
			EncodeGRPCFetchOrderInfoResponse,
			serverOptions...,
		),
		getserverlist: grpctransport.NewServer(
			endpoints.GetServerListEndpoint,
			DecodeGRPCGetServerListRequest,
			EncodeGRPCGetServerListResponse,
			serverOptions...,
		),
		getserverlink: grpctransport.NewServer(
			endpoints.GetServerLinkEndpoint,
			DecodeGRPCGetServerLinkRequest,
			EncodeGRPCGetServerLinkResponse,
			serverOptions...,
		),
		verifyorderfromchain: grpctransport.NewServer(
			endpoints.VerifyOrderFromChainEndpoint,
			DecodeGRPCVerifyOrderFromChainRequest,
			EncodeGRPCVerifyOrderFromChainResponse,
			serverOptions...,
		),
		cleanexpiredvpnlink: grpctransport.NewServer(
			endpoints.CleanExpiredVpnLinkEndpoint,
			DecodeGRPCCleanExpiredVpnLinkRequest,
			EncodeGRPCCleanExpiredVpnLinkResponse,
			serverOptions...,
		),
		getvpnconfig: grpctransport.NewServer(
			endpoints.GetVpnConfigEndpoint,
			DecodeGRPCGetVpnConfigRequest,
			EncodeGRPCGetVpnConfigResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the VpnsvcServer interface
type grpcServer struct {
	createorder          grpctransport.Handler
	updateorder          grpctransport.Handler
	vpninfo              grpctransport.Handler
	fetchorders          grpctransport.Handler
	fetchorderinfo       grpctransport.Handler
	getserverlist        grpctransport.Handler
	getserverlink        grpctransport.Handler
	verifyorderfromchain grpctransport.Handler
	cleanexpiredvpnlink  grpctransport.Handler
	getvpnconfig         grpctransport.Handler
}

// Methods for grpcServer to implement VpnsvcServer interface

func (s *grpcServer) CreateOrder(ctx context.Context, req *pb.CreateOrderRequest) (*pb.CreateOrderResponse, error) {
	_, rep, err := s.createorder.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.CreateOrderResponse), nil
}

func (s *grpcServer) UpdateOrder(ctx context.Context, req *pb.UpdateOrderRequest) (*pb.UpdateOrderResponse, error) {
	_, rep, err := s.updateorder.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.UpdateOrderResponse), nil
}

func (s *grpcServer) VpnInfo(ctx context.Context, req *pb.VpnInfoRequest) (*pb.VpnInfoResponse, error) {
	_, rep, err := s.vpninfo.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.VpnInfoResponse), nil
}

func (s *grpcServer) FetchOrders(ctx context.Context, req *pb.FetchOrdersRequest) (*pb.FetchOrdersResponse, error) {
	_, rep, err := s.fetchorders.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.FetchOrdersResponse), nil
}

func (s *grpcServer) FetchOrderInfo(ctx context.Context, req *pb.FetchOrderInfoRequest) (*pb.FetchOrderInfoResponse, error) {
	_, rep, err := s.fetchorderinfo.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.FetchOrderInfoResponse), nil
}

func (s *grpcServer) GetServerList(ctx context.Context, req *pb.GetServerListRequest) (*pb.GetServerListResponse, error) {
	_, rep, err := s.getserverlist.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.GetServerListResponse), nil
}

func (s *grpcServer) GetServerLink(ctx context.Context, req *pb.GetServerLinkRequest) (*pb.GetServerLinkResponse, error) {
	_, rep, err := s.getserverlink.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.GetServerLinkResponse), nil
}

func (s *grpcServer) VerifyOrderFromChain(ctx context.Context, req *pb.VerifyOrderFromChainRequest) (*pb.VerifyOrderFromChainResponse, error) {
	_, rep, err := s.verifyorderfromchain.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.VerifyOrderFromChainResponse), nil
}

func (s *grpcServer) CleanExpiredVpnLink(ctx context.Context, req *pb.CleanExpiredVpnLinkRequest) (*pb.CleanExpiredVpnLinkResponse, error) {
	_, rep, err := s.cleanexpiredvpnlink.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.CleanExpiredVpnLinkResponse), nil
}

func (s *grpcServer) GetVpnConfig(ctx context.Context, req *pb.GetVpnConfigRequest) (*pb.GetVpnConfigResponse, error) {
	_, rep, err := s.getvpnconfig.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.GetVpnConfigResponse), nil
}

// Server Decode

// DecodeGRPCCreateOrderRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC createorder request to a user-domain createorder request. Primarily useful in a server.
func DecodeGRPCCreateOrderRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.CreateOrderRequest)
	return req, nil
}

// DecodeGRPCUpdateOrderRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC updateorder request to a user-domain updateorder request. Primarily useful in a server.
func DecodeGRPCUpdateOrderRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.UpdateOrderRequest)
	return req, nil
}

// DecodeGRPCVpnInfoRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC vpninfo request to a user-domain vpninfo request. Primarily useful in a server.
func DecodeGRPCVpnInfoRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.VpnInfoRequest)
	return req, nil
}

// DecodeGRPCFetchOrdersRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC fetchorders request to a user-domain fetchorders request. Primarily useful in a server.
func DecodeGRPCFetchOrdersRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.FetchOrdersRequest)
	return req, nil
}

// DecodeGRPCFetchOrderInfoRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC fetchorderinfo request to a user-domain fetchorderinfo request. Primarily useful in a server.
func DecodeGRPCFetchOrderInfoRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.FetchOrderInfoRequest)
	return req, nil
}

// DecodeGRPCGetServerListRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC getserverlist request to a user-domain getserverlist request. Primarily useful in a server.
func DecodeGRPCGetServerListRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.GetServerListRequest)
	return req, nil
}

// DecodeGRPCGetServerLinkRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC getserverlink request to a user-domain getserverlink request. Primarily useful in a server.
func DecodeGRPCGetServerLinkRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.GetServerLinkRequest)
	return req, nil
}

// DecodeGRPCVerifyOrderFromChainRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC verifyorderfromchain request to a user-domain verifyorderfromchain request. Primarily useful in a server.
func DecodeGRPCVerifyOrderFromChainRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.VerifyOrderFromChainRequest)
	return req, nil
}

// DecodeGRPCCleanExpiredVpnLinkRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC cleanexpiredvpnlink request to a user-domain cleanexpiredvpnlink request. Primarily useful in a server.
func DecodeGRPCCleanExpiredVpnLinkRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.CleanExpiredVpnLinkRequest)
	return req, nil
}

// DecodeGRPCGetVpnConfigRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC getvpnconfig request to a user-domain getvpnconfig request. Primarily useful in a server.
func DecodeGRPCGetVpnConfigRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.GetVpnConfigRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCCreateOrderResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain createorder response to a gRPC createorder reply. Primarily useful in a server.
func EncodeGRPCCreateOrderResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.CreateOrderResponse)
	return resp, nil
}

// EncodeGRPCUpdateOrderResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain updateorder response to a gRPC updateorder reply. Primarily useful in a server.
func EncodeGRPCUpdateOrderResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.UpdateOrderResponse)
	return resp, nil
}

// EncodeGRPCVpnInfoResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain vpninfo response to a gRPC vpninfo reply. Primarily useful in a server.
func EncodeGRPCVpnInfoResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.VpnInfoResponse)
	return resp, nil
}

// EncodeGRPCFetchOrdersResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain fetchorders response to a gRPC fetchorders reply. Primarily useful in a server.
func EncodeGRPCFetchOrdersResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.FetchOrdersResponse)
	return resp, nil
}

// EncodeGRPCFetchOrderInfoResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain fetchorderinfo response to a gRPC fetchorderinfo reply. Primarily useful in a server.
func EncodeGRPCFetchOrderInfoResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.FetchOrderInfoResponse)
	return resp, nil
}

// EncodeGRPCGetServerListResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain getserverlist response to a gRPC getserverlist reply. Primarily useful in a server.
func EncodeGRPCGetServerListResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.GetServerListResponse)
	return resp, nil
}

// EncodeGRPCGetServerLinkResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain getserverlink response to a gRPC getserverlink reply. Primarily useful in a server.
func EncodeGRPCGetServerLinkResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.GetServerLinkResponse)
	return resp, nil
}

// EncodeGRPCVerifyOrderFromChainResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain verifyorderfromchain response to a gRPC verifyorderfromchain reply. Primarily useful in a server.
func EncodeGRPCVerifyOrderFromChainResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.VerifyOrderFromChainResponse)
	return resp, nil
}

// EncodeGRPCCleanExpiredVpnLinkResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain cleanexpiredvpnlink response to a gRPC cleanexpiredvpnlink reply. Primarily useful in a server.
func EncodeGRPCCleanExpiredVpnLinkResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.CleanExpiredVpnLinkResponse)
	return resp, nil
}

// EncodeGRPCGetVpnConfigResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain getvpnconfig response to a gRPC getvpnconfig reply. Primarily useful in a server.
func EncodeGRPCGetVpnConfigResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.GetVpnConfigResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
